ddol82/HealingDog-SpringBoot

src/main/java/com/healing/healingdog/HealingdogApplication.java
=> Feature/training 기본 틀 생성

build.gradle, src/main/java/com/healing/healingdog/common/file/model/dao/ImageMapper.java, src/main/java/com/healing/healingdog/common/file/model/dto/ImageDTO.java, src/main/java/com/healing/healingdog/common/file/model/dto/ImageType.java, src/main/java/com/healing/healingdog/common/util/ImageUtils.java, src/main/java/com/healing/healingdog/configuration/WebConfig.java, src/main/resources/application.yml, src/main/resources/mybatis/mapper/BoardImageMapper.xml, src/main/resources/mybatis/mybatis-config.xml
=> ✨ feat: 진행중 - 이미지 파일 모듈 작업

src/main/java/com/healing/healingdog/boarding/controller/BoardingController.java, src/main/java/com/healing/healingdog/boarding/dao/BoardingMapper.java, src/main/java/com/healing/healingdog/boarding/dto/BoardingBookingDTO.java, src/main/java/com/healing/healingdog/boarding/service/BoardingManageService.java, src/main/java/com/healing/healingdog/boarding/service/BoardingService.java, src/main/resources/mybatis/mapper/BoardingManageMapper.xml, src/main/resources/mybatis/mapper/BoardingMapper.xml, src/main/resources/mybatis/mybatis-config.xml
feat(boarding/{boarding_service_code}/booking CRUD): 위탁돌봄예약 등록, 삭제 작성완료
=> feat(boarding/{boarding_service_code}/booking CRUD): 위탁돌봄예약 등록, 삭제 작성완료

src/main/java/com/healing/healingdog/common/ResponseDTO.java, src/main/java/com/healing/healingdog/common/util/ImageUtils.java, src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dao/CommunityMapper.java, src/main/java/com/healing/healingdog/community/model/dto/BoardDTO.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/java/com/healing/healingdog/community/model/type/BoardType.java, src/main/resources/application.yml, src/main/resources/mybatis/mapper/CommunityMapper.xml
Controller 내 기능 개발을 포함하여 Service, Mapper, Mapper.xml 연동 테스트
=> 🎉 init: Controller to Mapper

src/main/java/com/healing/healingdog/common/ResponseDTO.java
공통 모듈 중 하나인 ResponseDTO를 수정하였습니다.
사용 중인 다른 Controller들에서는 기존 방식에서 변경하지 않아도 지장이 없고,
HTTP 상태 코드에 따른 추가 내용을 덧붙였습니다.
=> 🦄 refactor: 공통 모듈 ResponseDTO 수정

src/main/java/com/healing/healingdog/beauty/BeautyController.java, src/main/java/com/healing/healingdog/beauty/controller/BeautyController.java, src/main/java/com/healing/healingdog/beauty/controller/BeautyManageController.java, src/main/java/com/healing/healingdog/beauty/model/dao/BeautyManageMapper.java, src/main/java/com/healing/healingdog/beauty/model/dto/BeautyDTO.java, src/main/java/com/healing/healingdog/beauty/model/dto/CommonDTO.java, src/main/java/com/healing/healingdog/beauty/model/service/BeautyManageService.java, src/main/java/com/healing/healingdog/beauty/model/service/BeautyService.java, src/main/java/com/healing/healingdog/common/ResponseDTO.java
=> beauty commit test

src/main/java/com/healing/healingdog/common/ResponseDTO.java, src/main/java/com/healing/healingdog/common/paging/ItemWithPaging.java, src/main/java/com/healing/healingdog/common/paging/PageDataAutoFill.java, src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dao/CommunityMapper.java, src/main/java/com/healing/healingdog/community/model/dto/BoardDTO.java, src/main/java/com/healing/healingdog/community/model/dto/DetailForGettingBoard.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/resources/application.yml, src/main/resources/mybatis/mapper/CommunityMapper.xml, src/main/resources/mybatis/mybatis-config.xml
게시글 조회(List)를 추가하였고, 기존에 yml을 이용한 페이지 상수 처리를 하였는데,
@Value annotation은 Bean으로 등록 된 클래스를
BeanPostProcessor에 의해 처리시키므로 Bean으로 등록해야 합니다.
일단 공통으로 쓰는 부분이 아니기도 하고 일단 상수로 등록하였습니다.
=> ✨ feat: 게시글 조회 추가, yml 변경

src/main/java/com/healing/healingdog/beauty/controller/BeautyManageController.java, src/main/java/com/healing/healingdog/beauty/model/dao/BeautyManageMapper.java, src/main/java/com/healing/healingdog/beauty/model/dto/BeautyDTO.java, src/main/java/com/healing/healingdog/beauty/model/dto/CommonDTO.java, src/main/java/com/healing/healingdog/beauty/model/service/BeautyManageService.java, src/main/java/com/healing/healingdog/common/file/model/dto/CertificatesDTO.java, src/main/resources/mybatis/mapper/BeautyManageMapper.xml, src/main/resources/mybatis/mybatis-config.xml
미용실 정보 등록
미용실 정보 수정
미용실 카테고리 수정
밍요실 자격증 등록
미용실 자격증 수정
미용실 삭제
미용실 시간
등록
미용실 시간 조회
구현 완
=> feat: 0328 미용실 기능 구현

src/main/java/com/healing/healingdog/beauty/controller/BeautyManageController.java, src/main/java/com/healing/healingdog/beauty/model/dao/BeautyManageMapper.java, src/main/java/com/healing/healingdog/beauty/model/service/BeautyManageService.java, src/main/resources/mybatis/mapper/BeautyManageMapper.xml
=> feat: 03/30 아침회의 및 커밋

.gitignore, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java
* gitignore 설정의 변경을 적용하기 위해 commit합니다.
=> ✨ feat: 이미지 공통 모듈 진행(3)

src/main/java/com/healing/healingdog/beauty/controller/BeautyManageController.java, src/main/java/com/healing/healingdog/beauty/model/dao/BeautyManageMapper.java, src/main/java/com/healing/healingdog/beauty/model/service/BeautyManageService.java, src/main/java/com/healing/healingdog/jwt/TokenProvider.java, src/main/java/com/healing/healingdog/mypage/controller/MypetController.java, src/main/resources/mybatis/mapper/BeautyManageMapper.xml
=> feat: 04/04 아침회의

src/main/java/com/healing/healingdog/mypage/controller/MypetController.java, src/main/java/com/healing/healingdog/mypage/model/dao/MypetMapper.java, src/main/java/com/healing/healingdog/mypage/model/service/MypetService.java, src/main/resources/mybatis/mapper/MypetMapper.xml
=> 04-04 아침 2차 커밋푸쉬

src/main/java/com/healing/healingdog/common/util/ImageUtils.java, src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dto/BoardTableDTO.java, src/main/java/com/healing/healingdog/community/model/dto/ResultBoardDTO.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/java/com/healing/healingdog/configuration/SecurityConfig.java, src/main/java/com/healing/healingdog/mypage/controller/MypetController.java, src/main/resources/mybatis/mapper/CommunityMapper.xml
썸네일 리사이즈 결과물이 의도대로 나오지 않는 문제가 있었습니다.
결론은 css의 width, height를 max-width, max-height로 바꾸는 작업을 진행했고, 백엔드의 리사이즈 메소드가 작성이 완료되지 않아 발생한 현상이었습니다.
=> 🐞 fix: 썸네일 리사이즈 오류 수정

build.gradle, src/main/java/com/healing/healingdog/common/file/model/dto/ImageTableDTO.java, src/main/java/com/healing/healingdog/common/util/ImageUtils.java, src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dao/CommunityMapper.java, src/main/java/com/healing/healingdog/community/model/dto/LikeDTO.java, src/main/java/com/healing/healingdog/community/model/dto/ResultBoardDTO.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/java/com/healing/healingdog/configuration/SecurityConfig.java, src/main/resources/mybatis/mapper/BoardImageMapper.xml, src/main/resources/mybatis/mapper/CommunityMapper.xml, src/main/resources/mybatis/mybatis-config.xml
게시글 상세보기와 그에 따른 변화점들을 react, springboot 모두에 반영하였습니다. 이미지는 0장일 때, 1장일 때, 2장 이상일 때에 따라 표시되는 컴포넌트가 다르며,
좋아요의 경우 상태까지는 반영되었으나 로그인 여부를 확인하는 등의 작업은 다음에 반영이 필요할 것으로 보입니다.
=> ✨ feat: 게시글 상세보기 추가

src/main/java/com/healing/healingdog/healingcare/controller/UserHealingCareController.java, src/main/java/com/healing/healingdog/healingcare/model/dao/UserHealingCareMapper.java, src/main/java/com/healing/healingdog/healingcare/model/dto/HealingCareDTO.java, src/main/java/com/healing/healingdog/healingcare/model/dto/HealingCareFareDTO.java, src/main/java/com/healing/healingdog/healingcare/model/dto/HealingCareReservationDTO.java, src/main/java/com/healing/healingdog/healingcare/model/dto/PetSitterDTO.java, src/main/java/com/healing/healingdog/healingcare/model/service/UserHealingCareService.java
=> 04-07 아침 커밋푸쉬

src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dao/CommunityMapper.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/resources/application.yml, src/main/resources/mybatis/mapper/CommunityMapper.xml
게시글 공유 기능의 추가와,
이의 횟수 저장을 위한 로직이 추가되었습니다.
=> ✨ feat: 공유 기능 추가

src/main/java/com/healing/healingdog/common/util/ImageUtils.java, src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dao/CommunityMapper.java, src/main/java/com/healing/healingdog/community/model/dto/CommentDTO.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/resources/mybatis/mapper/CommunityMapper.xml, src/main/resources/mybatis/mybatis-config.xml
=> ✨ feat: 댓글 기능 추가

.gitignore, build.gradle, src/main/java/com/healing/healingdog/configuration/RestTemplateClient.java, src/main/java/com/healing/healingdog/login/controller/SmsController.java, src/main/java/com/healing/healingdog/login/model/dto/MessagesDTO.java, src/main/java/com/healing/healingdog/login/model/dto/RequestDTO.java, src/main/java/com/healing/healingdog/login/model/dto/SmsRequestDTO.java, src/main/java/com/healing/healingdog/login/model/dto/SmsResponseDTO.java, src/main/java/com/healing/healingdog/login/model/service/SmsService.java, src/main/resources/application.yml
=> 04-10 저녁 커밋푸쉬

src/main/java/com/healing/healingdog/mypage/controller/UserController.java, src/main/java/com/healing/healingdog/mypage/model/service/UserService.java, src/main/resources/mybatis/mapper/UserMapper.xml
마이페이지 내프로필 조회 수정 삭제 완료 작업중 변경점 반영
=> 04-12 아침 커밋푸쉬

src/main/java/com/healing/healingdog/common/file/model/dto/ImageFormDTO.java, src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dao/CommunityMapper.java, src/main/java/com/healing/healingdog/community/model/dto/BoardUpdateDTO.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/resources/mybatis/mapper/BoardImageMapper.xml, src/main/resources/mybatis/mapper/CommunityMapper.xml
게시글 수정 과정에서 사진을 처리하는 로직을 추가하였습니다.
- 변경 사항이 없는 경우 유지합니다.
- 새로 추가된 사진이 있다면 [변형된]usage로 추가합니다.
- 위치가 변경된 경우 변경된 위치의 [변형된]usage로 수정합니다.
- 기존 사진이 삭제된 경우 파일 삭제 및 DB정보 삭제를 반영하였습니다.
- [변형된]usage를 정상적인 숫자로 되돌립니다.
=> ✨ feat: 게시글 수정 기능 반영

src/main/java/com/healing/healingdog/community/controller/CommunityController.java, src/main/java/com/healing/healingdog/community/model/dao/CommunityMapper.java, src/main/java/com/healing/healingdog/community/model/service/CommunityService.java, src/main/resources/application.yml, src/main/resources/mybatis/mapper/BoardImageMapper.xml
사진 수정 로직에서 순서 변경을 통해 임시 변수를 불러오지 않아도 되는 방법이 있어 적용했습니다.
=> 🦄 refactor: 사진 수정 로직 수정

src/main/java/com/healing/healingdog/mypage/controller/MypetController.java, src/main/resources/application.yml
=> 04-14 아침 커밋 푸쉬

src/main/java/com/healing/healingdog/common/file/model/dto/ImageType.java, src/main/java/com/healing/healingdog/common/paging/ItemWithPaging.java, src/main/java/com/healing/healingdog/common/paging/PageData.java, src/main/java/com/healing/healingdog/common/util/ImageUtils.java, src/main/java/com/healing/healingdog/community/model/type/BoardType.java
기존 공통 모듈 중 문서가 존재하지 않는 클래스가 존재하여,
해당 클래스의 문서 주석을 추가하였습니다.
=> 📃 docs: 문서 주석 추가
